#! /bin/sh
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:    mountdevsubfs mountall
# Required-Stop:
# Should-Start:      
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO

export HOME="/root"
export ZYNTHIAN_DIR="/zynthian"
export FRAMEBUFFER="/dev/fb1"

do_start () {
  if [ -c $FRAMEBUFFER ]; then
    cat $ZYNTHIAN_DIR/zynthian-ui/img/fb1_zynthian.raw > $FRAMEBUFFER
  fi  
  rm -f $HOME/.remote_display_env
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac
