#! /bin/sh
### BEGIN INIT INFO
# Provides:          asplashscreen
# Required-Start:    mountdevsubfs mountall
# Required-Stop:
# Should-Start:      
# Default-Start:     S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description:       Show custom splashscreen
### END INIT INFO

#apt-get install fbi
#chmod a+x /etc/init.d/asplashscreen
#insserv /etc/init.d/asplashscreen

do_start () {
  if [ -c /dev/fb1 ]; then
    cat /home/pi/zynthian/zynthian-ui/img/fb1_zynthian.raw > /dev/fb1
  fi  
  rm -f /home/pi/.remote_display_env
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac
