#! /bin/sh
### BEGIN INIT INFO
# Provides:          zynthian
# Required-Start:
# Required-Stop:
# Should-Start:      
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Init Zynthian
# Description:       Init Zynthian
### END INIT INFO

export HOME="/root"
export ZYNTHIAN_DIR="/zynthian"
export FRAMEBUFFER="/dev/fb1"

zynthian_start () {
	cd $ZYNTHIAN_DIR/zynthian-ui
	startx ./zynthian.sh -- :0 vt3 &
}

zynthian_stop () {
	killall zynthian.sh
}

case "$1" in
	start|"")
		zynthian_start
		;;
	restart|reload|force-reload)
		echo "Error: argument '$1' not supported" >&2
		exit 3
		;;
  stop)
		zynthian_stop
		sleep 1
		;;
	status)
		exit 0
		;;
	*)
		echo "Usage: zynthian [start|stop]" >&2
		exit 3
		;;
esac
